nice_urls: false
plugins:
    enable:
        - simplecontact
    config:
        simplecontact:
            template: @site/layouts/simplecontact/form.twig
            subject: "Kontaktanfrage deiner Website!"
            recipient: "blackhole@example.com"
            fields:
              name:
                label: "Dein Name"
                placeholder: "Dein Name"
              email:
                label: "Deine E-Mail"
                placeholder: "Deine E-Mail"
              message:
                label: "Deine Nachricht"
                placeholder: "Deine Nachricht"
              antispam:
                label: "Antispam"
                placeholder: "Antispam"
              submit:
                label: "Formular absenden"
            messages:
              success: "Vielen Dank! Deine Nachricht wurde versendet."
              error: "Uups! Da gibt's ein Problem. Bitte vervollständige das Formular und probier's nochmal."
              fail: "Uups! Etwas ist schief gegangen. Das Nachricht konnte nicht übermittelt werden."
            errors:
              empty_field: "Dies ist ein Pflichtfeld"
              invalid_email: "Die eingegebene E-Mail ist ungültig"